const initialData = [
  {
    id: 1,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Commercial Data Provider",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 2,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2017",
    comments: "",
  },
  {
    id: 3,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2020",
    comments: "",
  },
  {
    id: 4,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 5,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 6,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Commercial Data Provider",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 7,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2017",
    comments: "",
  },
  {
    id: 8,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2020",
    comments: "",
  },
  {
    id: 9,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 10,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 11,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 12,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
];

export default initialData;
