const initialData = [
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Commercial Data Provider',
    categoryOfDoc: 'Annual Report',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2021',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'No',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Company Website',
    categoryOfDoc: 'Anti-Corruption',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2017',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Public Data Soruce',
    categoryOfDoc: 'Annual Report',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2020',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'No',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Company Website',
    categoryOfDoc: 'Anti-Corruption',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2019',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Public Data Soruce',
    categoryOfDoc: 'Code of Ethics and Business',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2021',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Commercial Data Provider',
    categoryOfDoc: 'Annual Report',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2021',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'No',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Company Website',
    categoryOfDoc: 'Anti-Corruption',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2017',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Public Data Soruce',
    categoryOfDoc: 'Annual Report',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2020',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'No',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Company Website',
    categoryOfDoc: 'Anti-Corruption',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2019',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Public Data Soruce',
    categoryOfDoc: 'Code of Ethics and Business',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2021',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'No',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Company Website',
    categoryOfDoc: 'Anti-Corruption',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2019',
    comments: '',
  },
  {
    bvd9Id: '2964',
    veId: 'US0394831020',
    companyName: 'Archer Daniels Midland',
    stdDoc: 'Yes',
    nameOfDoc: 'XYZ',
    sourceOfDoc: 'Public Data Soruce',
    categoryOfDoc: 'Code of Ethics and Business',
    urlOfDoc: 'www.archer.com/123#',
    publishedYear: '2021',
    comments: '',
  },
];

export default initialData;
