const initialData = [
  {
    id: 1,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Commercial Data Provider",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 2,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2017",
    comments: "",
  },
  {
    id: 3,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2020",
    comments: "",
  },
  {
    id: 4,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 5,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 6,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Commercial Data Provider",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 7,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2017",
    comments: "",
  },
  {
    id: 8,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Annual Report",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2020",
    comments: "",
  },
  {
    id: 9,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 10,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
  {
    id: 11,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "No",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Company Website",
    categoryOfDoc: "Anti-Corruption",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2019",
    comments: "",
  },
  {
    id: 12,
    bvd9Id: "2964",
    veId: "US0394831020",
    companyName: "Archer Daniels Midland",
    stdDoc: "Yes",
    nameOfDoc: "XYZ",
    sourceOfDoc: "Public Data Soruce",
    categoryOfDoc: "Code of Ethics and Business",
    urlOfDoc: "www.archer.com/123#",
    publishedYear: "2021",
    comments: "",
  },
];

const categoryOfDocumentItems = [
  {
    title: "Annual Report",
    value: "Annual Report",
  },
  {
    title: "Anti-Corruption",
    value: "Anti-Corruption",
  },
  {
    title: "Code of Ethiics and Business conduct & Advertisings",
    value: "Code of Ethiics and Business conduct & Advertisings",
  },
  {
    title: "Corporate governance report & charter",
    value: "Corporate governance report & charter",
  },
  {
    title: "Diversity Report",
    value: "Diversity Report",
  },
  {
    title: "Fiscal Contribution",
    value: "Fiscal Contribution",
  },
  {
    title: "Forest Policy",
    value: "Forest Policy",
  },
  {
    title: "Health and Safety",
    value: "Health and Safety",
  },
  {
    title: "Human Right",
    value: "Human Right",
  },
  {
    title: "Other",
    value: "Other",
  },
  {
    title: "Sustainability Plan",
    value: "Sustainability Plan",
  },
  {
    title: "Sustainability Report",
    value: "Sustainability Report",
  },
  {
    title: "Technology",
    value: "Technology",
  },
  {
    title: "Whistlerblower Policy",
    value: "Whistlerblower Policy",
  },
];

const publishedYearItems = [
  {
    title: "1980",
    value: "1980",
  },
  {
    title: "2000",
    value: "2000",
  },
  {
    title: "2001",
    value: "2001",
  },
  {
    title: "2002",
    value: "2002",
  },
  {
    title: "2003",
    value: "2003",
  },
  {
    title: "2005",
    value: "2005",
  },
];

export { categoryOfDocumentItems, initialData, publishedYearItems };
